Gradle, AndroidX, minSDK, Annotations, gitignore
adroitandroid/Near pull request #10
Opened 2019-08-21 18:52 UTC by DATL4G

did as written in first commit
updated README for better looking and newer information

(maybe change version in README if you push it to v1.2)

2019-08-21 18:55 UTC, DATL4G commented
Please merge this PR so it's a bit updated and better to use for those who fork it or just use it

Tested with multiple Android Smartphones on different versions and an Android TV with sdk 26

2019-09-04 02:20 UTC, adroitandroid requested changes
apart from the comments below, rest looks good

2019-09-04 02:20 UTC, adroitandroid commented on app/src/main/java/com/adroitandroid/p2pchat/ChatAdapter.java
> +        MessageVH(@NotNull RowMessagesBinding binding) {
why not use the android @NonNull instead https://developer.android.com/reference/androidx/annotation/NonNull.html

2019-09-04 02:20 UTC, adroitandroid commented on near/src/main/java/com/adroitandroid/near/connect/TcpServerService.java
> +import androidx.annotation.Nullable;
at other places, we can use the NonNull sibling of this instead of from the jetbrains annotations

2019-09-04 14:08 UTC, DATL4G commented
Requested changes done.
Ready to merge

2019-09-09 10:56 UTC, adroitandroid commented on near/src/main/java/com/adroitandroid/near/model/Host.java
> +import org.jetbrains.annotations.Nullable;
missed out here

2019-09-09 12:54 UTC, DATL4G commented on near/src/main/java/com/adroitandroid/near/model/Host.java
> +import org.jetbrains.annotations.Nullable;
Done

2019-09-10 03:01 UTC, merged

2019-09-10 14:17 UTC, DATL4G commented
@adroitandroid Could you create the v1.2 release please?

2019-09-19 10:13 UTC, adroitandroid commented
again late to see this, lemme do it, give me till this weekend

2019-10-01 17:00 UTC, DATL4G commented
@adroitandroid 
Its nearly 2 weeks now.
Even if you have less time its just setting a new tag and maybe provide a description.
Should be done in less than 5 min.
JIT builds itself when someone requests this release.

Till then I have to stick to my fork

2019-10-01 17:26 UTC, adroitandroid commented
extremely sorry @DATL4G , saw the mail now, had forgotten till then. On it 👍